export {default as AuthorizationPage} from './AuthorizationPage';
export {default as RegistrationPage} from './RegistrationPage';
export {default as BlogPage} from './BlogPage';
export {default as RoutesPage} from './RoutesPage';
export {default as ProfilePage} from './ProfilePage';
export {default as MainPage} from './MainPage';
export {default as NotFoundPage} from './NotFoundPage';
export {default as RouteDetailsPage} from './RouteDetailsPage';
export {default as CreatingRoute} from './CreatingRoute';