export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const REGISTRATION = 'REGISTRATION';
export const LOGIN = 'LOGIN';
export const AUTH = 'AUTH';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const GET_USER_ROUTES = 'GET_USER_ROUTES';
export const DELETE_MY_ROUTE = 'DELETE_MY_ROUTE';
export const PUBLISH_MY_ROUTE = 'PUBLISH_MY_ROUTE';
export const COMPLETE_ROUTE = 'COMPLETE_ROUTE';

export const setUser = (userName) => ({type: SET_USER, payload: userName});
export const logout = () => ({type: LOGOUT});
export const registration = (values) => ({type: REGISTRATION, payload: values});
export const login = (values) => ({type: LOGIN, payload: values});
export const auth = () => ({type: AUTH});
export const GetUserRoute = () => ({type: GET_USER_ROUTES});
export const SaveUserData = (data) => ({type: SAVE_USER_DATA, payload: data});
export const deleteMyRoute = (id) => ({type: DELETE_MY_ROUTE, payload: id});
export const publishMyRoute = (id) => ({type: PUBLISH_MY_ROUTE, payload: id});
export const completeRoute = (id) => ({type: COMPLETE_ROUTE, payload: id });